export const LGA_DATA = [
  {
    id: "akoko-edo",
    name: "Akoko-Edo",
    description:
      "Located in the north of Edo State, Akoko-Edo is known for its agricultural activities and scenic landscapes. The LGA is a gateway to the northern region with rich biodiversity.",
    landmarks: ["Ikpeshi Pottery Site", "Akoko River", "Northern Forest Reserve"],
    activities: ["Agriculture", "Pottery", "Tourism"],
    image: "/akoko-edo-landscape-forest.jpg",
    mapX: 200,
    mapY: 120,
  },
  {
    id: "owan-west",
    name: "Owan West",
    description:
      "A developing LGA with rich natural resources, Owan West balances conservation with economic development.",
    landmarks: ["Natural Resources", "Development Projects", "Community Centers"],
    activities: ["Mining", "Agriculture", "Conservation"],
    image: "/owan-forest-landscape.jpg",
    mapX: 320,
    mapY: 140,
  },
  {
    id: "owan-east",
    name: "Owan East",
    description:
      "Part of the eastern region, Owan East is characterized by forest reserves and agricultural communities.",
    landmarks: ["Forest Reserves", "Eco-tourism Sites", "Traditional Villages"],
    activities: ["Forestry", "Eco-tourism", "Agriculture"],
    image: "/forest-reserve-nature.jpg",
    mapX: 440,
    mapY: 130,
  },
  {
    id: "etsako-west",
    name: "Etsako West",
    description:
      "A vibrant LGA with strong agricultural base and emerging commercial activities, Etsako West is experiencing rapid growth.",
    landmarks: ["Fugar Town", "Agricultural Markets", "Trading Posts"],
    activities: ["Agriculture", "Trading", "Transport"],
    image: "/market-trading-rural-commerce.jpg",
    mapX: 280,
    mapY: 200,
  },
  {
    id: "etsako-central",
    name: "Etsako Central",
    description:
      "Located in the central north, Etsako Central is a growing economic zone with agricultural and commercial activities.",
    landmarks: ["Auchi Town", "Auchi Polytechnic", "Market Centers"],
    activities: ["Education", "Commerce", "Agriculture"],
    image: "/auchi-town-polytechnic.jpg",
    mapX: 380,
    mapY: 200,
  },
  {
    id: "etsako-east",
    name: "Etsako East",
    description:
      "Part of the Etsako region, this LGA is known for its resourcefulness and community-driven development initiatives.",
    landmarks: ["Igarra Town", "Natural Springs", "Community Centers"],
    activities: ["Tourism", "Agriculture", "Community Service"],
    image: "/natural-spring-tourism-resort.jpg",
    mapX: 500,
    mapY: 160,
  },
  {
    id: "esan-north-east",
    name: "Esan North-East",
    description:
      "Characterized by farming communities and traditional settlements, Esan North-East preserves rich cultural practices and agricultural heritage.",
    landmarks: ["Ekpoma Town", "Traditional Markets", "Esan Cultural Center"],
    activities: ["Farming", "Crafts", "Education"],
    image: "/ekpoma-traditional-settlement.jpg",
    mapX: 550,
    mapY: 220,
  },
  {
    id: "esan-central",
    name: "Esan Central",
    description:
      "Home to Irrua, Esan Central is known for its healthcare facilities and agricultural production. The Esan people maintain rich traditions and craftsmanship.",
    landmarks: ["Irrua Specialist Teaching Hospital", "Esan Shrine", "Agricultural Markets"],
    activities: ["Healthcare", "Agriculture", "Weaving"],
    image: "/esan-central-village-traditional.jpg",
    mapX: 520,
    mapY: 280,
  },
  {
    id: "esan-west",
    name: "Esan West",
    description:
      "A blend of urban and rural settings, Esan West is actively developing with improved infrastructure and economic opportunities.",
    landmarks: ["Ewohimi Town", "Development Projects", "Market Centers"],
    activities: ["Commerce", "Infrastructure", "Small Industries"],
    image: "/town-development-market.jpg",
    mapX: 450,
    mapY: 300,
  },
  {
    id: "esan-south-east",
    name: "Esan South-East",
    description:
      "Known for its agricultural productivity and cultural festivals, Esan South-East showcases the warmth and hospitality of the Esan people.",
    landmarks: ["Uzebba Market", "Seasonal Festivals", "Agricultural Fields"],
    activities: ["Agriculture", "Trading", "Hospitality"],
    image: "/agricultural-harvest-farming.jpg",
    mapX: 580,
    mapY: 340,
  },
  {
    id: "uhunmwonde",
    name: "Uhunmwonde",
    description:
      "Known for its agricultural productivity and scenic beauty, Uhunmwonde is an emerging center for agricultural commerce.",
    landmarks: ["Agricultural Markets", "Scenic Landscapes", "Community Groups"],
    activities: ["Agriculture", "Agro-tourism", "Trade"],
    image: "/agricultural-landscape.jpg",
    mapX: 380,
    mapY: 380,
  },
  {
    id: "igueben",
    name: "Igueben",
    description:
      "Known for its peaceful communities and agricultural ventures, Igueben is gradually developing as an economic center.",
    landmarks: ["Igueben Town", "Farming Communities", "Local Markets"],
    activities: ["Agriculture", "Livestock", "Crafts"],
    image: "/livestock-farming-pastoral.jpg",
    mapX: 480,
    mapY: 360,
  },
  {
    id: "oredo",
    name: "Oredo",
    description:
      "The heart of Benin City, Oredo is the administrative and cultural center of Edo State, featuring the historic Oba's Palace and major institutions.",
    landmarks: ["Oba's Palace", "National Museum", "Government Secretariat"],
    activities: ["Government", "Culture", "Tourism"],
    image: "/oba-palace-historic-architecture.jpg",
    mapX: 380,
    mapY: 380,
  },
  {
    id: "egor",
    name: "Egor",
    description:
      "Part of Benin City, Egor is a vibrant urban center with commercial activities and cultural heritage. It serves as a major economic hub in the state.",
    landmarks: ["Benin City Central", "Commercial District", "Cultural Sites"],
    activities: ["Commerce", "Trade", "Arts and Crafts"],
    image: "/benin-city-urban-market.jpg",
    mapX: 400,
    mapY: 360,
  },
  {
    id: "ikpoba-okha",
    name: "Ikpoba-Okha",
    description:
      "Part of greater Benin City area, Ikpoba-Okha combines urban development with cultural preservation and commercial activities.",
    landmarks: ["Ugbowo Campus", "Urban Centers", "Cultural Sites"],
    activities: ["Education", "Commerce", "Urban Services"],
    image: "/university-campus-urban-city.jpg",
    mapX: 420,
    mapY: 400,
  },
  {
    id: "orhionmwon",
    name: "Orhionmwon",
    description:
      "A semi-urban LGA with agricultural activities and traditional settlements, Orhionmwon maintains strong community ties and cultural practices.",
    landmarks: ["Sabongida-Ora Town", "Traditional Councils", "Rural Markets"],
    activities: ["Agriculture", "Community Services", "Local Government"],
    image: "/rural-community-traditional.jpg",
    mapX: 480,
    mapY: 440,
  },
  {
    id: "ovia-north-east",
    name: "Ovia North-East",
    description:
      "Known for agricultural production and coastal influences, Ovia North-East is developing tourism and agricultural sectors.",
    landmarks: ["Coastal Areas", "Rubber Plantations", "Fishing Communities"],
    activities: ["Agriculture", "Fishing", "Tourism"],
    image: "/coastal-fishing-village-beach.jpg",
    mapX: 580,
    mapY: 420,
  },
  {
    id: "ovia-south-west",
    name: "Ovia South-West",
    description:
      "Located in the southern part, Ovia South-West features agricultural lands and emerging commercial zones.",
    landmarks: ["Agricultural Zones", "Market Towns", "Rural Communities"],
    activities: ["Agriculture", "Forestry", "Small Businesses"],
    image: "/forest-agriculture-southern.jpg",
    mapX: 480,
    mapY: 480,
  },
];
